# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
      #  cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.4
    - name: Set up texlive
      uses: paolobrasolin/setup-texlive-action@v1
      with:
        profile-path: ${{ github.workspace }}/.github/texlive.profile
        packages-path: ${{ github.workspace }}/.github/texlive.packages
    - name: update apt 
      run: sudo apt-get update -y
    - name: install additional packages 
      run: sudo apt-get install -y transfig gnuplot inkscape

    # - name: install additional packages 
    #   uses: awalsh128/cache-apt-pkgs-action@latest
    #   with:
    #     packages: transfig gnuplot inkscape

    # - name: prepare with maven 
    #   run: mvn -B verify #validate latex:grp
    #   working-directory: ./maven-latex-plugin
    # - name: compile with latexmk
    #   run: latexmk latexmk
    #   working-directory: ./maven-latex-plugin/src/site/tex/fdbLatexmk

    # This is a check without diff. 
    # It merely ensures that the plugin runs without errors 
    - name: Build with Maven
      run: mvn -B validate latex:cfg --file pom.xml #-Dmaven.test.skip=true
      # Note that the tests are not necessary, but ... used a different pom. 
      working-directory: ./maven-latex-plugin

    # This is with diff also. 
    # It does work for xfigFormat.tex, robustsample.tex, latexEngines.tex, latexEngines.tex, 
    # but not for useBeamerPres.tex 
    # I suspect, it has to do with different versions of packages. 
    # So for the moment what follows must be deactivated. 
    # - name: Prepare with maven 
    #   run: mvn -B validate # to create the proper pom: pom4pdf.xml
    #   working-directory: ./maven-latex-plugin
    # - name: Build with Maven
    #   run: mvn -B latex:cfg --file ./src/test/resources/integration/pom4pdf.xml #-Dmaven.test.skip=true
    #   # Note that the tests are not necessary, but ... used a different pom. 
    #   working-directory: ./maven-latex-plugin

    # Optional: Uploads the full dependency graph to GitHub 
    # to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
